flight_analytics:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: trino
      port: 8080
      user: dbt
      catalog: iceberg
      schema: airline
      threads: 4
